#!/bin/bash
# Check if user is root
if [[ $EUID -ne 0 ]]; then
    echo "You must be a root user to run this." 2>&1
    exit 1
fi
# Confirm if system is booted in efi mode
ls /sys/firmware/efi/efivars
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
#
cat <<EOT >> /root/arch/chroot
#!/bin/bash
# Check if script is being run as root
if [[ $EUID -ne 0 ]]; then
    echo "Run this script as root." 2>&1
    exit 1
fi
# Set the timezone to US-Pacific
ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime
# Generate /etc/adjtime
hwclock --systohc --utc
# Uncomment locale
echo "Setting locale: en_US.UTF-8 UTF-8 for American-English."
sed -i '/#en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
echo
# Set the LANG variable
echo "LANG=en_US.UTF-8"  > /etc/locale.conf
# Generate locale
locale-gen
echo
# Set hostname
echo $hostname > /etc/hostname
# Input root password
echo "Enter root password."
passwd
echo
# Create /boot/efi directory
mkdir /boot/efi
# Mount efi partition to the /boot/efi directory
mount $efipartition /boot/efi
echo
# Install some required packages for booting and stuff
yes "" | pacman -S --needed intel-ucode grub efibootmgr sudo networkmanager os-prober wget
echo
# Install grub to /boot/efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=$bootloaderid
echo
# Change grub timeout to 3
sudo sed -i '4s/5/0/' /etc/default/grub
# Generate grub config file
sudo grub-mkconfig -o /boot/grub/grub.cfg
echo
# Enable network manager
systemctl enable NetworkManager
# Create user
useradd -m -g users -G wheel -s /bin/bash $username
echo
# Input user password
echo Enter your user password.
passwd $username
echo
# Set admin priviliges
echo "Uncommenting the wheel group line."
sudo sed -i '/# %wheel ALL=(ALL) ALL/s/^#//g' /etc/sudoers
# Exit chroot
exit
EOT
#
# Make /root/arch/chroot executable
chmod +x /root/arch/chroot
