#!/bin/bash
# Check if script is being run as root
if [[ $EUID -ne 0 ]]; then
    echo "Run this script as root." 2>&1
    exit 1
fi
# Check if system is booted in efi mode
echo "ls /sys/firmware/efi/efivars"
ls /sys/firmware/efi/efivars
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
# Update system clock
timedatectl set-ntp true
# List partitions
fdisk -l
echo
lsblk
echo
# Edit partitions
echo "cfdisk"
read
cfdisk
# List partitions
fdisk -l
echo
lsblk
# Edit partitions
echo "cfdisk"
read
cfdisk
# List partitions
fdisk -l
echo
lsblk
echo
# Input location of efi partition
read -p "efipartition (/dev/sdax) = " efipartition
echo $efipartition
echo
# Input location of root partition
read -p "ospartition (/dev/sdax) = " ospartition
echo $ospartition
echo
# Input bootloader id
read -p "Enter your preferred bootloader-id: " bootloaderid
echo $bootloaderid
echo
# Input hostname
read -p "Enter your hostname: " hostname
echo $hostname
echo
# Input username
read -p "Enter your preferred username: " username
echo $username
echo
# Format efi partition as fat32
echo mkfs.fat -F32 $efipartition
mkfs.fat -F32 $efipartition
echo
# Format root partition as ext4
echo mkfs.ext4 $ospartition
mkfs.ext4 $ospartition
echo
# Mount root partition to /mnt
mount $ospartition /mnt
# Install the base and base-devel package groups using pacstrap
echo "pacstrap /mnt base base-devel"
pacstrap /mnt base base-devel
echo
# Generate fstab
echo "Generate fstab."
genfstab -U /mnt >> /mnt/etc/fstab
echo
cat /mnt/etc/fstab
# Enter input into chroot file
cat << EOT >> /root/arch/chroot
stuff to put in chroot file
EOT
#
sudo sed -i "25s@inputhostname@$hostname@" /root/arch/chroot
sudo sed -i "33s@inputefipartition@$efipartition@" /root/arch/chroot
sudo sed -i "39s@inputbootloaderid@$bootloaderid@" /root/arch/chroot
sudo sed -i "49s@inputusername@$username@" /root/arch/chroot
sudo sed -i "53s@inputusername@$username@" /root/arch/chroot
#
sudo sed -i "59s@inputusername@$username@" /root/arch/chroot
sudo sed -i "60s@inputusername@$username@" /root/arch/chroot
sudo sed -i "61s@inputusername@$username@" /root/arch/chroot
sudo sed -i "62s@inputusername@$username@" /root/arch/chroot
sudo sed -i "63s@inputusername@$username@" /root/arch/chroot
sudo sed -i "64s@inputusername@$username@" /root/arch/chroot
sudo sed -i "65s@inputusername@$username@" /root/arch/chroot
sudo sed -i "66s@inputusername@$username@" /root/arch/chroot
# Make remaining installation files executable
chmod +x /root/arch/*
#chmod +x /root/arch/chroot
#chmod +x /root/arch/gnome1
#chmod +x /root/arch/gnome2
#chmod +x /root/arch/kde1
#chmod +x /root/arch/kde2
#chmod +x /root/arch/i3xfce1
#chmod +x /root/arch/i3xfce2
#chmod +x /root/arch/budgie1
#chmod +x /root/arch/budgie2
# Copy remaining installation files to /mnt
cp -a /root/arch/. /mnt
#cp /root/install/chroot /mnt
#cp /root/install/gnome1 /mnt
#cp /root/install/gnome2 /mnt
#cp /root/install/kde1 /mnt
#cp /root/install/kde2 /mnt
#cp /root/install/i3xfce1 /mnt
#cp /root/install/i3xfce2 /mnt
#cp /root/install/budgie1 /mnt
#cp /root/install/budgie2 /mnt
rm -r /root/arch
# Run the chroot script in the new system through chroot 
arch-chroot /mnt ./chroot
# Unmount and reboot
umount -a
reboot
